# Generated by Django 4.0 on 2021-12-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oznakowanie', models.IntegerField(unique=True, verbose_name='Oznakowanie')),
                ('kategoria', models.CharField(choices=[('Lekka', 'L'), ('Ciężka', 'H')], max_length=30, verbose_name='Kategoria')),
                ('pHwKCL', models.FloatField(null=True)),
                ('potrz_wapn', models.CharField(choices=[('Potrzebne', 'P'), ('Ograniczone', 'O'), ('Zbędne', 'Z')], max_length=30, verbose_name='Potrz_wapn')),
                ('p2o5', models.FloatField(null=True, verbose_name='P2O5')),
                ('k2o', models.FloatField(null=True, verbose_name='K2O')),
                ('mg', models.FloatField(null=True, verbose_name='Mg')),
                ('b', models.FloatField(null=True, verbose_name='B')),
                ('mn', models.FloatField(null=True, verbose_name='Mn')),
                ('cu', models.FloatField(null=True, verbose_name='Cu')),
                ('zn', models.FloatField(null=True, verbose_name='Zn')),
                ('fe', models.FloatField(null=True, verbose_name='Fe')),
                ('lat', models.FloatField(null=True, verbose_name='Lattitude')),
                ('long', models.FloatField(null=True, verbose_name='Longitude')),
            ],
        ),
    ]
